const COLOR_PRIMARY = '#00ADEE';
const COLOR_SECONDARY = '#333333';
const COLOR_WHITE = '#FFFFFF';
const COLOR_DANGER = '#FF4751';
const COLOR_GREY = '#A0A0A0';
const COLOR_LIGHT_GREY = '#CCCCCC';
const COLOR_OCEAN = '#35D5F5';
const COLOR_TRANSPARENT = 'rgba(0, 0, 0, 0.05)';

export {
  COLOR_PRIMARY,
  COLOR_SECONDARY,
  COLOR_WHITE,
  COLOR_DANGER,
  COLOR_GREY,
  COLOR_LIGHT_GREY,
  COLOR_OCEAN,
  COLOR_TRANSPARENT,
};
